first: all

CFLAGS=-I.. -I$(PCRTREE)/include

EXAMPLE_TARGET=csf
OBJS=  _row.o \
   border.o \
   create2.o \
   csfdump1.o \
   csfdump2.o \
   csfstat.o \
   dupbool.o \
   maskdump.o \
   rawbin.o \
   rcreate.o \
   row.o \
   rreadas.o \
   set_min.o \
   somecell.o \
   testcsf.o 

include $(PCRTREE)/template/make/makexmpl
