NATIVE_PATH($ENV{RASTERFORMAT} RASTERFORMAT_PROJECT)
GET_FILENAME_COMPONENT(_BASE_NAME ${RASTERFORMAT_PROJECT} NAME)
NATIVE_PATH($ENV{OBJECTS}/${_BASE_NAME} _RASTERFORMAT_OBJECTS)

INCLUDE_DIRECTORIES(
  ${RASTERFORMAT_PROJECT}/Sources/PCRasterRasterFormat
)

FIND_LIBRARY(PCRASTER_RASTERFORMAT_LIBRARY
  NAMES PCRasterRasterFormat
  PATHS ${_RASTERFORMAT_OBJECTS}/bin
  NO_DEFAULT_PATH
)

