NATIVE_PATH($ENV{RASTERFORMAT} RASTERFORMAT_PROJECT)
GET_FILENAME_COMPONENT(_BASE_NAME ${RASTERFORMAT_PROJECT} NAME)
IF(RASTERFORMAT_ROOT)
    NATIVE_PATH(${RASTERFORMAT_ROOT} _RASTERFORMAT_OBJECTS)
ELSE()
    NATIVE_PATH($ENV{OBJECTS}/${_BASE_NAME} _RASTERFORMAT_OBJECTS)
ENDIF()

INCLUDE_DIRECTORIES(
  ${RASTERFORMAT_PROJECT}/Sources/PCRasterRasterFormat
)

FIND_LIBRARY(PCRASTER_RASTERFORMAT_LIBRARY
  NAMES PCRasterRasterFormat
  PATHS
      ${_RASTERFORMAT_OBJECTS}/bin/${CMAKE_BUILD_TYPE}
      ${_RASTERFORMAT_OBJECTS}/bin
  NO_DEFAULT_PATH
)

